server:
  port: 9091
app:
    message: Message sent to the RabbitMQ queue Successfully
spring:
    rabbitmq:
      host: localhost
      password: guest
      port: 15672
      username: guest
      exchange: user.exchange
      queue: user.queue
      routingkey: user.routingkey


